name: Release

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.VectorTiles/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.VectorTiles.Mapbox/